import assert from "node:assert/strict";
import test from "node:test";
import Fastify from "fastify";
import jwt from "@fastify/jwt";
import QRCode from "qrcode";
import { createHmac } from "node:crypto";
import { mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import ticketExportRoutes from "./ticket-exports.js";

test("ticket PNG export enforces ownership, PNG limits, scoped expiring links and attachment bytes", async () => {
  const directory = await mkdtemp(path.join(tmpdir(), "ticket-export-test-"));
  await writeFile(path.join(directory, "c".repeat(32) + "." + (Date.now() - 1000) + ".png"), "expired fixture");
  const secret = "synthetic-export-test-secret";
  const app = Fastify();
  await app.register(jwt, { secret });
  app.decorate("authenticate", async (request, reply) => {
    try { await request.jwtVerify(); } catch { reply.code(401).send({ success: false }); }
  });
  app.register(ticketExportRoutes, { prefix: "/api/ticket-exports", secret, directory,
    isOwnedConfirmed: async (userId, id) => userId === 11 && id === 803,
  });
  const authorization = "Bearer " + app.jwt.sign({ id: 11, email: "qa@example.test", role: "general" });
  const png = await QRCode.toBuffer("QA-TICKET-803");
  const upload = (body = png, id = 803, bearer = authorization) => app.inject({ method: "POST",
    url: "/api/ticket-exports/registrations/" + id, headers: { authorization: bearer, "content-type": "image/png" }, payload: body,
  });
  try {
    assert.equal((await upload(png, 803, "Bearer invalid")).statusCode, 401);
    assert.equal((await upload(png, 804)).statusCode, 404);
    assert.equal((await upload(Buffer.from("not a PNG"))).statusCode, 400);
    assert.equal((await upload(Buffer.alloc(3 * 1024 * 1024 + 1))).statusCode, 413);
    const large = Buffer.from(png); large.writeUInt32BE(9000, 16);
    assert.equal((await upload(large)).statusCode, 400);
    const created = await upload();
    assert.equal(created.statusCode, 201);
    const link = created.json().path;
    assert.match(link, /^\/api\/ticket-exports\/[a-f0-9]{32}\.\d{13}\.[A-Za-z0-9_-]{43}$/);
    assert.equal(created.headers["cache-control"], "private, no-store");
    const downloaded = await app.inject({ url: link });
    assert.equal(downloaded.statusCode, 200);
    assert.equal(downloaded.headers["content-type"], "image/png");
    assert.equal(downloaded.headers["content-disposition"], 'attachment; filename="PRIS2026-Ticket.png"');
    assert.equal(downloaded.headers["x-content-type-options"], "nosniff");
    assert.equal(downloaded.headers["referrer-policy"], "no-referrer");
    assert.deepEqual(downloaded.rawPayload, png);
    const [file] = await readdir(directory);
    assert.equal((await readdir(directory)).length, 1, "startup removes expired exports");
    assert.deepEqual(await readFile(path.join(directory, file)), png);
    const tampered = link.slice(0, -1) + (link.endsWith("0") ? "1" : "0");
    assert.equal((await app.inject({ url: tampered })).statusCode, 404);
    assert.equal((await app.inject({ url: "/api/ticket-exports/../../secret" })).statusCode, 404);
    assert.equal((await upload(png, 803, "Bearer " + link.split("/").at(-1))).statusCode, 401);
    const expired = "a".repeat(32) + "." + (Date.now() - 1000);
    const sig = createHmac("sha256", secret).update("ticket-export:" + expired).digest("base64url");
    assert.equal((await app.inject({ url: "/api/ticket-exports/" + expired + "." + sig })).statusCode, 410);
    const absent = "b".repeat(32) + "." + (Date.now() + 60_000);
    const missingSig = createHmac("sha256", secret).update("ticket-export:" + absent).digest("base64url");
    assert.equal((await app.inject({ url: "/api/ticket-exports/" + absent + "." + missingSig })).statusCode, 410);
  } finally {
    await app.close();
    // Exact temporary directory generated by mkdtemp above; contains only this test's files.
    await rm(directory, { recursive: true, force: true });
  }
});
