-- Durable abstract tracking allocator.
-- Manual migration: run only after read-only preflight and reviewed namespace/floor
-- batch. Do not run drizzle-kit generate/db:push for this change.
BEGIN;

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

-- The API/runtime role must not create objects in the namespace used by the
-- SECURITY DEFINER functions. Deployment roles may grant this back explicitly
-- only for a controlled migration session.
REVOKE CREATE ON SCHEMA public FROM PUBLIC;

DO $$
BEGIN
  IF to_regclass('public.abstract_tracking_migration_batches') IS NULL
     OR NOT EXISTS (
       SELECT 1 FROM abstract_tracking_migration_batches WHERE frozen_at IS NOT NULL
     ) THEN
    RAISE EXCEPTION '0028 requires a frozen reviewed abstract-tracking manifest';
  END IF;
END
$$;

-- A prior interrupted/rehearsed run may already have installed this trigger.
-- PostgreSQL cannot alter a column type while a trigger definition depends on it.
DROP TRIGGER IF EXISTS abstracts_guard_legacy_tracking_id ON abstracts;

ALTER TABLE abstracts
  ALTER COLUMN tracking_id TYPE varchar(80);

ALTER TABLE abstracts
  ADD COLUMN IF NOT EXISTS archived_at timestamptz,
  ADD COLUMN IF NOT EXISTS archived_by integer REFERENCES backoffice_users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS archive_reason varchar(40),
  ADD COLUMN IF NOT EXISTS archive_note text,
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

ALTER TABLE events
  ADD COLUMN IF NOT EXISTS archived_at timestamptz,
  ADD COLUMN IF NOT EXISTS archived_by integer REFERENCES backoffice_users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS archive_reason varchar(40),
  ADD COLUMN IF NOT EXISTS archive_note text;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'abstracts_id_event_unique') THEN
    ALTER TABLE abstracts ADD CONSTRAINT abstracts_id_event_unique UNIQUE (id, event_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'abstracts_archive_state_check') THEN
    ALTER TABLE abstracts ADD CONSTRAINT abstracts_archive_state_check CHECK (
      (archived_at IS NULL AND archive_reason IS NULL AND archive_note IS NULL AND archived_by IS NULL)
      OR (archived_at IS NOT NULL AND archive_reason IS NOT NULL AND btrim(archive_reason) <> '')
    );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'events_archive_state_check') THEN
    ALTER TABLE events ADD CONSTRAINT events_archive_state_check CHECK (
      (archived_at IS NULL AND archive_reason IS NULL AND archive_note IS NULL AND archived_by IS NULL)
      OR (archived_at IS NOT NULL AND archive_reason IS NOT NULL AND btrim(archive_reason) <> '')
    );
  END IF;
END
$$;

DO $$
BEGIN
  CREATE TYPE abstract_tracking_identifier_origin AS ENUM
    ('native', 'legacy_structured', 'legacy_opaque', 'recovery_tombstone');
EXCEPTION WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE abstract_tracking_assignment_reason AS ENUM
    ('initial_submission', 'presentation_type_change', 'legacy_import',
     'migration_assignment', 'migration_normalization', 'admin_correction');
EXCEPTION WHEN duplicate_object THEN NULL;
END
$$;

CREATE TABLE IF NOT EXISTS abstract_tracking_namespaces (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id integer NOT NULL REFERENCES events(id) ON DELETE RESTRICT,
  prefix varchar(50) NOT NULL,
  padding_width smallint NOT NULL DEFAULT 3,
  locked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT abstract_tracking_namespaces_prefix_check
    CHECK (prefix <> '' AND prefix = btrim(prefix)
      AND prefix ~ '^[A-Z0-9]+(?:-[A-Z0-9]+)*$'),
  CONSTRAINT abstract_tracking_namespaces_width_check
    CHECK (padding_width BETWEEN 1 AND 12)
);

CREATE UNIQUE INDEX IF NOT EXISTS abstract_tracking_namespaces_event_unique
  ON abstract_tracking_namespaces(event_id);
CREATE UNIQUE INDEX IF NOT EXISTS abstract_tracking_namespaces_prefix_ci_unique
  ON abstract_tracking_namespaces(lower(prefix));

CREATE TABLE IF NOT EXISTS abstract_tracking_counters (
  namespace_id bigint NOT NULL REFERENCES abstract_tracking_namespaces(id) ON DELETE RESTRICT,
  presentation_type presentation_type NOT NULL,
  last_issued_number bigint NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (namespace_id, presentation_type),
  CONSTRAINT abstract_tracking_counters_nonnegative_check
    CHECK (last_issued_number >= 0)
);

CREATE TABLE IF NOT EXISTS abstract_tracking_allocations (
  tracking_id varchar(80) PRIMARY KEY,
  event_id integer REFERENCES events(id) ON DELETE RESTRICT,
  presentation_type presentation_type,
  sequence_number bigint,
  identifier_origin abstract_tracking_identifier_origin NOT NULL,
  allocated_at timestamptz NOT NULL DEFAULT now(),
  metadata jsonb,
  CONSTRAINT abstract_tracking_allocations_structured_check CHECK (
    (identifier_origin = 'recovery_tombstone')
    OR (identifier_origin = 'legacy_opaque' AND event_id IS NOT NULL)
    OR (event_id IS NOT NULL AND presentation_type IS NOT NULL AND sequence_number > 0)
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS abstract_tracking_allocations_tuple_unique
  ON abstract_tracking_allocations(event_id, presentation_type, sequence_number)
  WHERE sequence_number IS NOT NULL;

CREATE TABLE IF NOT EXISTS abstract_tracking_identifiers (
  tracking_id varchar(80) PRIMARY KEY
    REFERENCES abstract_tracking_allocations(tracking_id) ON DELETE RESTRICT,
  abstract_id integer NOT NULL REFERENCES abstracts(id) ON DELETE RESTRICT,
  event_id integer NOT NULL REFERENCES events(id) ON DELETE RESTRICT,
  presentation_type_at_assignment presentation_type NOT NULL,
  previous_tracking_id varchar(80),
  reason abstract_tracking_assignment_reason NOT NULL,
  assigned_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT abstract_tracking_identifiers_not_self_check
    CHECK (previous_tracking_id IS NULL OR previous_tracking_id <> tracking_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS abstract_tracking_identifiers_abstract_tracking_unique
  ON abstract_tracking_identifiers(abstract_id, event_id, presentation_type_at_assignment, tracking_id);
CREATE UNIQUE INDEX IF NOT EXISTS abstract_tracking_identifiers_one_root_unique
  ON abstract_tracking_identifiers(abstract_id)
  WHERE previous_tracking_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS abstract_tracking_identifiers_one_successor_unique
  ON abstract_tracking_identifiers(previous_tracking_id)
  WHERE previous_tracking_id IS NOT NULL;

CREATE OR REPLACE FUNCTION abstract_tracking_append_only()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public, pg_temp
AS $$
BEGIN
  RAISE EXCEPTION '% is append-only', TG_TABLE_NAME
    USING ERRCODE = '42501', DETAIL = TG_TABLE_NAME;
END;
$$;

DROP TRIGGER IF EXISTS abstract_tracking_allocations_append_only ON abstract_tracking_allocations;
CREATE TRIGGER abstract_tracking_allocations_append_only
BEFORE UPDATE OR DELETE ON abstract_tracking_allocations
FOR EACH ROW EXECUTE FUNCTION abstract_tracking_append_only();

DROP TRIGGER IF EXISTS abstract_tracking_identifiers_append_only ON abstract_tracking_identifiers;
CREATE TRIGGER abstract_tracking_identifiers_append_only
BEFORE UPDATE OR DELETE ON abstract_tracking_identifiers
FOR EACH ROW EXECUTE FUNCTION abstract_tracking_append_only();

CREATE OR REPLACE FUNCTION abstract_tracking_assignment_guard()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
  v_allocation abstract_tracking_allocations%ROWTYPE;
  v_previous abstract_tracking_identifiers%ROWTYPE;
BEGIN
  SELECT * INTO v_allocation
  FROM abstract_tracking_allocations
  WHERE tracking_id = NEW.tracking_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'tracking allocation does not exist' USING ERRCODE = '23503';
  END IF;
  IF v_allocation.event_id IS NOT NULL AND v_allocation.event_id <> NEW.event_id THEN
    RAISE EXCEPTION 'tracking allocation belongs to another event' USING ERRCODE = '23514';
  END IF;
  IF v_allocation.identifier_origin = 'native'
     AND v_allocation.presentation_type IS DISTINCT FROM NEW.presentation_type_at_assignment THEN
    RAISE EXCEPTION 'native tracking allocation type mismatch' USING ERRCODE = '23514';
  END IF;
  IF NEW.previous_tracking_id IS NULL THEN
    IF NEW.reason IN ('presentation_type_change', 'migration_normalization', 'admin_correction') THEN
      RAISE EXCEPTION 'assignment reason requires a predecessor' USING ERRCODE = '23514';
    END IF;
  ELSE
    IF NEW.reason IN ('initial_submission', 'legacy_import', 'migration_assignment') THEN
      RAISE EXCEPTION 'assignment reason cannot have a predecessor' USING ERRCODE = '23514';
    END IF;
    SELECT * INTO v_previous
    FROM abstract_tracking_identifiers
    WHERE tracking_id = NEW.previous_tracking_id;
    IF NOT FOUND OR v_previous.abstract_id <> NEW.abstract_id OR v_previous.event_id <> NEW.event_id THEN
      RAISE EXCEPTION 'tracking predecessor does not belong to the same abstract/event' USING ERRCODE = '23514';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS abstract_tracking_assignment_guard ON abstract_tracking_identifiers;
CREATE TRIGGER abstract_tracking_assignment_guard
BEFORE INSERT ON abstract_tracking_identifiers
FOR EACH ROW EXECUTE FUNCTION abstract_tracking_assignment_guard();

CREATE OR REPLACE FUNCTION abstract_tracking_allocation_has_assignment()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public, pg_temp
AS $$
BEGIN
  IF NEW.identifier_origin <> 'recovery_tombstone'
     AND NOT EXISTS (
       SELECT 1 FROM abstract_tracking_identifiers i
       WHERE i.tracking_id = NEW.tracking_id
     ) THEN
    RAISE EXCEPTION 'tracking allocation has no assignment' USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS abstract_tracking_allocation_assignment_deferred ON abstract_tracking_allocations;
CREATE CONSTRAINT TRIGGER abstract_tracking_allocation_assignment_deferred
AFTER INSERT OR UPDATE ON abstract_tracking_allocations
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION abstract_tracking_allocation_has_assignment();

CREATE OR REPLACE FUNCTION abstract_tracking_append_assignment(
  p_tracking_id varchar,
  p_abstract_id integer,
  p_event_id integer,
  p_presentation_type presentation_type,
  p_previous_tracking_id varchar,
  p_reason abstract_tracking_assignment_reason
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
  v_current_tracking_id varchar(80);
BEGIN
  SELECT a.tracking_id INTO v_current_tracking_id
  FROM abstracts a
  WHERE a.id = p_abstract_id AND a.event_id = p_event_id
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'abstract/event assignment target not found' USING ERRCODE = '23503';
  END IF;
  IF (p_previous_tracking_id IS NULL AND v_current_tracking_id IS DISTINCT FROM p_tracking_id)
     OR (p_previous_tracking_id IS NOT NULL AND p_previous_tracking_id IS DISTINCT FROM v_current_tracking_id) THEN
    RAISE EXCEPTION 'tracking assignment predecessor is not the current abstract identifier' USING ERRCODE = '23514';
  END IF;
  INSERT INTO abstract_tracking_identifiers (
    tracking_id, abstract_id, event_id, presentation_type_at_assignment,
    previous_tracking_id, reason
  ) VALUES (
    p_tracking_id, p_abstract_id, p_event_id, p_presentation_type,
    p_previous_tracking_id, p_reason
  );
END;
$$;

CREATE TABLE IF NOT EXISTS abstract_tracking_runtime (
  singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton = true),
  allocator_enabled boolean NOT NULL DEFAULT false,
  allocator_version smallint NOT NULL DEFAULT 1,
  history_ready boolean NOT NULL DEFAULT false,
  legacy_bridge_enabled boolean NOT NULL DEFAULT true,
  abstract_writes_paused boolean NOT NULL DEFAULT false,
  write_pause_reason varchar(64),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT abstract_tracking_runtime_pause_reason_check CHECK (
    (abstract_writes_paused = true AND write_pause_reason IS NOT NULL)
    OR (abstract_writes_paused = false AND write_pause_reason IS NULL)
  )
);

INSERT INTO abstract_tracking_runtime (singleton)
VALUES (true)
ON CONFLICT (singleton) DO NOTHING;

CREATE TABLE IF NOT EXISTS abstract_tracking_approved_floors (
  event_id integer NOT NULL REFERENCES events(id) ON DELETE RESTRICT,
  presentation_type presentation_type NOT NULL,
  approved_floor bigint NOT NULL CHECK (approved_floor >= 0),
  evidence_source text NOT NULL,
  approved_by text NOT NULL,
  approved_at timestamptz NOT NULL,
  approval_reason text NOT NULL,
  PRIMARY KEY (event_id, presentation_type)
);

CREATE TABLE IF NOT EXISTS abstract_tracking_audit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type varchar(64) NOT NULL,
  event_id integer REFERENCES events(id) ON DELETE SET NULL,
  abstract_id integer REFERENCES abstracts(id) ON DELETE SET NULL,
  actor_type varchar(24) NOT NULL,
  actor_id integer,
  request_id varchar(128),
  reason_code varchar(64),
  before_state jsonb,
  after_state jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT abstract_tracking_audit_event_type_check CHECK (event_type IN (
    'abstract_tracking.issued',
    'abstract_tracking.rotated',
    'abstract_tracking.prefix_configured',
    'abstract_tracking.prefix_locked',
    'abstract_tracking.admin_corrected',
    'abstract_tracking.recovery_tombstone_imported',
    'abstract_tracking.migration_imported',
    'abstract_tracking.migration_normalized',
    'abstract_tracking.floor_applied',
    'abstract_tracking.cutover_completed',
    'abstract_tracking.legacy_bridge_changed',
    'abstract_tracking.hardening_completed',
    'abstract_tracking.write_pause_changed',
    'abstract.archived',
    'abstract.restored',
    'abstract.member_unlinked',
    'event.archived',
    'event.restored'
  ))
);

CREATE TABLE IF NOT EXISTS abstract_submission_idempotency_keys (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  idempotency_key varchar(128) NOT NULL,
  request_fingerprint varchar(64) NOT NULL,
  abstract_id integer NOT NULL REFERENCES abstracts(id) ON DELETE RESTRICT,
  response_body jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT abstract_submission_idempotency_user_key_unique UNIQUE (user_id, idempotency_key)
);

DROP TRIGGER IF EXISTS abstract_tracking_audit_append_only ON abstract_tracking_audit_events;
CREATE TRIGGER abstract_tracking_audit_append_only
BEFORE UPDATE OR DELETE ON abstract_tracking_audit_events
FOR EACH ROW EXECUTE FUNCTION abstract_tracking_append_only();

-- Consume the latest frozen operator-approved namespace/floor batch. Existing
-- issued namespaces cannot be changed by this statement.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM abstract_tracking_namespaces n
    JOIN abstract_tracking_manifest_namespaces m ON m.event_id = n.event_id
    JOIN abstract_tracking_migration_batches b ON b.migration_batch_id = m.migration_batch_id
    WHERE b.frozen_at IS NOT NULL
      AND b.frozen_at = (SELECT max(frozen_at) FROM abstract_tracking_migration_batches WHERE frozen_at IS NOT NULL)
      AND n.locked_at IS NOT NULL
      AND (n.prefix <> m.prefix OR n.padding_width <> m.padding_width)
  ) THEN
    RAISE EXCEPTION 'reviewed namespace conflicts with an already locked namespace';
  END IF;
END
$$;

INSERT INTO abstract_tracking_namespaces (event_id, prefix, padding_width)
SELECT m.event_id, m.prefix, m.padding_width
FROM abstract_tracking_manifest_namespaces m
JOIN abstract_tracking_migration_batches b ON b.migration_batch_id = m.migration_batch_id
WHERE b.frozen_at IS NOT NULL
  AND b.frozen_at = (SELECT max(frozen_at) FROM abstract_tracking_migration_batches WHERE frozen_at IS NOT NULL)
ON CONFLICT (event_id) DO UPDATE
SET prefix = EXCLUDED.prefix,
    padding_width = EXCLUDED.padding_width,
    updated_at = clock_timestamp()
WHERE abstract_tracking_namespaces.locked_at IS NULL;

INSERT INTO abstract_tracking_approved_floors (
  event_id, presentation_type, approved_floor, evidence_source,
  approved_by, approved_at, approval_reason
)
SELECT m.event_id, m.presentation_type, m.approved_floor, m.evidence_source,
       m.approved_by, m.approved_at, m.approval_reason
FROM abstract_tracking_manifest_floors m
JOIN abstract_tracking_migration_batches b ON b.migration_batch_id = m.migration_batch_id
WHERE b.frozen_at IS NOT NULL
  AND b.frozen_at = (SELECT max(frozen_at) FROM abstract_tracking_migration_batches WHERE frozen_at IS NOT NULL)
ON CONFLICT (event_id, presentation_type) DO UPDATE
SET approved_floor = GREATEST(abstract_tracking_approved_floors.approved_floor, EXCLUDED.approved_floor),
    evidence_source = EXCLUDED.evidence_source,
    approved_by = EXCLUDED.approved_by,
    approved_at = EXCLUDED.approved_at,
    approval_reason = EXCLUDED.approval_reason;

-- Bootstrap namespaces/counters from existing event codes. Unsafe legacy event
-- codes intentionally remain unconfigured; submit then fails closed until an
-- operator sets a reviewed namespace. Existing IDs are imported byte-for-byte.
INSERT INTO abstract_tracking_namespaces (event_id, prefix, padding_width)
SELECT e.id, e.event_code, 3
FROM events e
WHERE e.event_code ~ '^[A-Z0-9]+(?:-[A-Z0-9]+)*$'
  AND EXISTS (SELECT 1 FROM abstracts a WHERE a.event_id = e.id AND a.tracking_id IS NOT NULL)
ON CONFLICT (event_id) DO NOTHING;

INSERT INTO abstract_tracking_counters (namespace_id, presentation_type)
SELECT n.id, t.presentation_type
FROM abstract_tracking_namespaces n
CROSS JOIN (VALUES ('oral'::presentation_type), ('poster'::presentation_type)) AS t(presentation_type)
ON CONFLICT (namespace_id, presentation_type) DO NOTHING;

INSERT INTO abstract_tracking_allocations (
  tracking_id, event_id, presentation_type, sequence_number, identifier_origin, metadata
)
SELECT
  a.tracking_id,
  a.event_id,
  CASE m.parts[2] WHEN 'O' THEN 'oral'::presentation_type ELSE 'poster'::presentation_type END,
  m.parts[3]::bigint,
  'legacy_structured',
  jsonb_build_object('source', '0028_backfill')
FROM abstracts a
JOIN abstract_tracking_namespaces n ON n.event_id = a.event_id
CROSS JOIN LATERAL regexp_match(a.tracking_id, '^(.+)-([OP])([0-9]{1,18})$') AS m(parts)
WHERE a.tracking_id IS NOT NULL
  AND m.parts[1] = n.prefix
ON CONFLICT (tracking_id) DO NOTHING;

INSERT INTO abstract_tracking_allocations (
  tracking_id, event_id, identifier_origin, metadata
)
SELECT a.tracking_id, a.event_id, 'legacy_opaque', jsonb_build_object('source', '0028_backfill')
FROM abstracts a
WHERE a.tracking_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM abstract_tracking_allocations x WHERE x.tracking_id = a.tracking_id
  )
ON CONFLICT (tracking_id) DO NOTHING;

INSERT INTO abstract_tracking_identifiers (
  tracking_id, abstract_id, event_id, presentation_type_at_assignment, reason
)
SELECT a.tracking_id, a.id, a.event_id, a.presentation_type, 'legacy_import'
FROM abstracts a
JOIN abstract_tracking_allocations x ON x.tracking_id = a.tracking_id
WHERE a.tracking_id IS NOT NULL
ON CONFLICT (tracking_id) DO NOTHING;

UPDATE abstract_tracking_counters c
SET last_issued_number = GREATEST(
  c.last_issued_number,
  COALESCE((
    SELECT MAX(a.sequence_number)
    FROM abstract_tracking_allocations a
    JOIN abstract_tracking_namespaces n ON n.id = c.namespace_id
    WHERE a.event_id = n.event_id
      AND a.presentation_type = c.presentation_type
      AND a.sequence_number IS NOT NULL
  ), 0)
),
updated_at = clock_timestamp()
WHERE c.namespace_id IS NOT NULL;

-- A reviewed floor is authoritative evidence for deleted/exported identifiers.
-- Never lower a counter; the next value is strictly floor + 1.
UPDATE abstract_tracking_counters c
SET last_issued_number = GREATEST(c.last_issued_number, f.approved_floor),
    updated_at = clock_timestamp()
FROM abstract_tracking_namespaces n
JOIN abstract_tracking_approved_floors f ON f.event_id = n.event_id
WHERE c.namespace_id = n.id AND f.presentation_type = c.presentation_type;

INSERT INTO abstract_tracking_audit_events (
  event_type, event_id, actor_type, reason_code, after_state
)
SELECT 'abstract_tracking.floor_applied', f.event_id, 'migration', 'approved_floor',
       jsonb_build_object('presentationType', f.presentation_type, 'approvedFloor', f.approved_floor,
                          'evidenceSource', f.evidence_source, 'approvedBy', f.approved_by)
FROM abstract_tracking_approved_floors f
WHERE NOT EXISTS (
  SELECT 1 FROM abstract_tracking_audit_events a
  WHERE a.event_type = 'abstract_tracking.floor_applied'
    AND a.event_id = f.event_id
    AND a.reason_code = 'approved_floor'
    AND a.after_state ->> 'presentationType' = f.presentation_type::text
);

UPDATE abstract_tracking_namespaces n
SET locked_at = COALESCE(n.locked_at, clock_timestamp()),
    updated_at = clock_timestamp()
WHERE EXISTS (
  SELECT 1 FROM abstract_tracking_allocations a
  WHERE a.event_id = n.event_id
);

UPDATE abstract_tracking_namespaces n
SET locked_at = COALESCE(n.locked_at, clock_timestamp()),
    updated_at = clock_timestamp()
WHERE EXISTS (
  SELECT 1 FROM abstract_tracking_counters c
  JOIN abstract_tracking_approved_floors f
    ON f.event_id = n.event_id
   AND f.presentation_type = c.presentation_type
  WHERE c.namespace_id = n.id AND f.approved_floor > 0
);

CREATE OR REPLACE FUNCTION abstract_tracking_touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = clock_timestamp();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS abstracts_touch_updated_at ON abstracts;
CREATE TRIGGER abstracts_touch_updated_at
BEFORE UPDATE ON abstracts
FOR EACH ROW EXECUTE FUNCTION abstract_tracking_touch_updated_at();

CREATE OR REPLACE FUNCTION abstract_tracking_counter_monotonic()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'abstract tracking counters are append-only' USING ERRCODE = '42501';
  END IF;
  IF NEW.namespace_id <> OLD.namespace_id
     OR NEW.presentation_type <> OLD.presentation_type
     OR NEW.last_issued_number < OLD.last_issued_number THEN
    RAISE EXCEPTION 'abstract tracking counter cannot move backward or change key' USING ERRCODE = '23514';
  END IF;
  NEW.updated_at = clock_timestamp();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS abstract_tracking_counter_monotonic ON abstract_tracking_counters;
CREATE TRIGGER abstract_tracking_counter_monotonic
BEFORE UPDATE OR DELETE ON abstract_tracking_counters
FOR EACH ROW EXECUTE FUNCTION abstract_tracking_counter_monotonic();

CREATE OR REPLACE FUNCTION abstract_tracking_namespace_immutable()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public, pg_temp
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF OLD.locked_at IS NOT NULL OR EXISTS (
      SELECT 1 FROM abstract_tracking_allocations a
      WHERE a.event_id = OLD.event_id
    ) THEN
      RAISE EXCEPTION 'issued tracking namespace cannot be deleted' USING ERRCODE = '42501';
    END IF;
    RETURN OLD;
  END IF;
  IF OLD.locked_at IS NOT NULL AND (
    NEW.event_id <> OLD.event_id OR NEW.prefix <> OLD.prefix OR NEW.padding_width <> OLD.padding_width
  ) THEN
    RAISE EXCEPTION 'issued tracking namespace is immutable' USING ERRCODE = '23514';
  END IF;
  IF OLD.locked_at IS NOT NULL AND NEW.locked_at IS NULL THEN
    RAISE EXCEPTION 'issued tracking namespace cannot be unlocked' USING ERRCODE = '23514';
  END IF;
  NEW.updated_at = clock_timestamp();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS abstract_tracking_namespace_immutable ON abstract_tracking_namespaces;
CREATE TRIGGER abstract_tracking_namespace_immutable
BEFORE UPDATE OR DELETE ON abstract_tracking_namespaces
FOR EACH ROW EXECUTE FUNCTION abstract_tracking_namespace_immutable();

CREATE OR REPLACE FUNCTION abstract_tracking_allocate(
  p_event_id integer,
  p_presentation_type presentation_type
)
RETURNS TABLE (
  tracking_id varchar,
  event_id integer,
  presentation_type presentation_type,
  sequence_number bigint,
  prefix varchar,
  padding_width smallint
)
LANGUAGE plpgsql
VOLATILE
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
  v_namespace abstract_tracking_namespaces%ROWTYPE;
  v_counter abstract_tracking_counters%ROWTYPE;
  v_max bigint;
  v_next bigint;
  v_marker text;
  v_tracking_id varchar(80);
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM abstract_tracking_runtime
    WHERE singleton = true AND allocator_enabled = true
  ) THEN
    RAISE EXCEPTION 'abstract tracking allocator is not enabled'
      USING ERRCODE = 'P0001';
  END IF;

  SELECT n.* INTO v_namespace
  FROM abstract_tracking_namespaces n
  WHERE n.event_id = p_event_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'abstract tracking namespace not configured for event %', p_event_id
      USING ERRCODE = 'P0001';
  END IF;

  SELECT c.* INTO v_counter
  FROM abstract_tracking_counters c
  WHERE c.namespace_id = v_namespace.id
    AND c.presentation_type = p_presentation_type
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'abstract tracking counter not configured for event % type %', p_event_id, p_presentation_type
      USING ERRCODE = 'P0001';
  END IF;

  SELECT COALESCE(MAX(a.sequence_number), 0)
    INTO v_max
  FROM abstract_tracking_allocations a
  WHERE a.event_id = p_event_id
    AND a.presentation_type = p_presentation_type
    AND a.sequence_number IS NOT NULL;

  v_next := GREATEST(v_counter.last_issued_number, v_max) + 1;
  v_marker := CASE p_presentation_type WHEN 'oral' THEN 'O' ELSE 'P' END;

  LOOP
    v_tracking_id := v_namespace.prefix || '-' || v_marker ||
      repeat('0', GREATEST(v_namespace.padding_width - length(v_next::text), 0)) || v_next::text;

    INSERT INTO abstract_tracking_allocations (
      tracking_id, event_id, presentation_type, sequence_number, identifier_origin
    ) VALUES (
      v_tracking_id, p_event_id, p_presentation_type, v_next, 'native'
    ) ON CONFLICT ON CONSTRAINT abstract_tracking_allocations_pkey DO NOTHING;

    IF FOUND THEN
      UPDATE abstract_tracking_counters AS c
      SET last_issued_number = v_next,
          updated_at = clock_timestamp()
        WHERE c.namespace_id = v_namespace.id
        AND c.presentation_type = p_presentation_type;
      UPDATE abstract_tracking_namespaces
      SET locked_at = COALESCE(locked_at, clock_timestamp()),
          updated_at = clock_timestamp()
      WHERE id = v_namespace.id;
      RETURN QUERY SELECT v_tracking_id, p_event_id, p_presentation_type,
        v_next, v_namespace.prefix, v_namespace.padding_width;
      RETURN;
    END IF;

    v_next := v_next + 1;
    IF v_next < 0 OR v_next > 9223372036854775806 THEN
      RAISE EXCEPTION 'abstract tracking sequence exhausted' USING ERRCODE = '22003';
    END IF;
  END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION abstract_tracking_guard_legacy_id()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
  v_match text[];
  v_namespace abstract_tracking_namespaces%ROWTYPE;
  v_counter abstract_tracking_counters%ROWTYPE;
  v_type presentation_type;
  v_number bigint;
BEGIN
  IF NEW.tracking_id IS NULL THEN
    RETURN NEW;
  END IF;

  IF EXISTS (
    SELECT 1 FROM abstract_tracking_runtime
    WHERE singleton = true AND abstract_writes_paused = true
  ) THEN
    RAISE EXCEPTION 'abstract writes are paused' USING ERRCODE = 'P0001';
  END IF;

  IF EXISTS (SELECT 1 FROM abstract_tracking_allocations a WHERE a.tracking_id = NEW.tracking_id) THEN
    RETURN NEW;
  END IF;

  v_match := regexp_match(NEW.tracking_id, '^(.+)-([OP])([0-9]+)$');
  IF v_match IS NULL THEN
    RAISE EXCEPTION 'legacy tracking identifier is not in the approved format' USING ERRCODE = '23514';
  END IF;

  v_type := CASE v_match[2] WHEN 'O' THEN 'oral'::presentation_type ELSE 'poster'::presentation_type END;
  IF v_type <> NEW.presentation_type THEN
    RAISE EXCEPTION 'tracking marker does not match presentation type' USING ERRCODE = '23514';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM abstract_tracking_runtime
    WHERE singleton = true AND legacy_bridge_enabled = true
  ) THEN
    RAISE EXCEPTION 'legacy tracking writer is disabled' USING ERRCODE = 'P0001';
  END IF;

  SELECT * INTO v_namespace
  FROM abstract_tracking_namespaces n
  WHERE n.event_id = NEW.event_id
    AND n.prefix = v_match[1]
  FOR UPDATE;
  IF NOT FOUND THEN
    RETURN NEW;
  END IF;

  v_number := v_match[3]::bigint;

  SELECT * INTO v_counter
  FROM abstract_tracking_counters c
  WHERE c.namespace_id = v_namespace.id
    AND c.presentation_type = v_type
  FOR UPDATE;

  IF FOUND AND v_number <= v_counter.last_issued_number THEN
    RAISE EXCEPTION 'legacy tracking number is below reserved floor' USING ERRCODE = '23505';
  END IF;

  IF FOUND THEN
    INSERT INTO abstract_tracking_allocations (
      tracking_id, event_id, presentation_type, sequence_number, identifier_origin, metadata
    ) VALUES (
      NEW.tracking_id, NEW.event_id, v_type, v_number, 'legacy_structured',
      jsonb_build_object('source', 'legacy_bridge')
    ) ON CONFLICT (tracking_id) DO NOTHING;
    UPDATE abstract_tracking_counters
    SET last_issued_number = GREATEST(last_issued_number, v_number),
        updated_at = clock_timestamp()
    WHERE namespace_id = v_namespace.id AND presentation_type = v_type;

    -- Pre-Release-A binaries insert the abstract with NULL and then update the
    -- identifier. Bridge that legacy write into the durable root assignment in
    -- the same transaction; no orphan allocation may commit.
    IF TG_OP = 'UPDATE' AND OLD.tracking_id IS NULL THEN
      INSERT INTO abstract_tracking_identifiers (
        tracking_id, abstract_id, event_id, presentation_type_at_assignment,
        previous_tracking_id, reason
      ) VALUES (
        NEW.tracking_id, NEW.id, NEW.event_id, NEW.presentation_type,
        NULL, 'migration_assignment'
      ) ON CONFLICT (tracking_id) DO NOTHING;
      INSERT INTO abstract_tracking_audit_events (
        event_type, event_id, abstract_id, actor_type, reason_code, after_state
      ) VALUES (
        'abstract_tracking.migration_imported', NEW.event_id, NEW.id, 'legacy_bridge',
        'legacy_bridge', jsonb_build_object('trackingId', NEW.tracking_id)
      );
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS abstracts_guard_legacy_tracking_id ON abstracts;
CREATE TRIGGER abstracts_guard_legacy_tracking_id
BEFORE INSERT OR UPDATE OF tracking_id, presentation_type ON abstracts
FOR EACH ROW EXECUTE FUNCTION abstract_tracking_guard_legacy_id();

REVOKE ALL ON FUNCTION abstract_tracking_allocate(integer, presentation_type) FROM PUBLIC;
REVOKE ALL ON FUNCTION abstract_tracking_append_assignment(varchar, integer, integer, presentation_type, varchar, abstract_tracking_assignment_reason) FROM PUBLIC;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'conference_api_runtime') THEN
    EXECUTE 'GRANT EXECUTE ON FUNCTION abstract_tracking_allocate(integer, presentation_type) TO conference_api_runtime';
    EXECUTE 'GRANT EXECUTE ON FUNCTION abstract_tracking_append_assignment(varchar, integer, integer, presentation_type, varchar, abstract_tracking_assignment_reason) TO conference_api_runtime';
  END IF;
END
$$;

UPDATE abstract_tracking_runtime
SET allocator_enabled = true,
    history_ready = false,
    legacy_bridge_enabled = true,
    abstract_writes_paused = true,
    write_pause_reason = 'tracking migration',
    updated_at = clock_timestamp()
WHERE singleton = true;

COMMIT;
