import assert from 'node:assert/strict';
import test from 'node:test';
import { randomUUID } from 'node:crypto';
import Fastify from 'fastify';
import jwt from '@fastify/jwt';
import multipart from '@fastify/multipart';
import sharp from 'sharp';
import { PDFDocument } from 'pdf-lib';
import { ApiError } from '../../errors/ApiError.js';
import { preparePresentationScenario } from './test-support.js';
import { reconcilePresentations } from './reconcile.js';
import { presentationOwnerRoutes } from './public.routes.js';
import { presentationBackofficeRoutes } from './backoffice.routes.js';
import { runPresentationMailOnce } from './email-jobs.js';
import type { OwnerPresentationDto, PresentationDetailDto, PresentationListDto, PresentationPreviewDto, RevisionDto, UploadDto } from './types.js';

test('synthetic full HTTP workflow: reconcile alias, two works/mail, rejected PNG, initial/revision PDF, cancel, replay and retained history', { timeout: 30000 }, async t => {
  const { client: sql, database, fixture: f, announcement } = await preparePresentationScenario(t);
  const [second] = await sql`INSERT INTO abstracts(event_id,user_id,tracking_id,title,presentation_type)
    VALUES(${f.eventId},${f.ownerId},'PRIS-2026-P002','Second synthetic work','poster') RETURNING id`;
  await sql`INSERT INTO abstract_tracking_identifiers(tracking_id,abstract_id,event_id) VALUES('OLD-P002',${second.id},${f.eventId})`;
  const alias = { ...announcement, id: 2, sequence: 2, trackingId: 'OLD-P002', title: 'Second synthetic work', round: 2 as const };
  await reconcilePresentations(database, [announcement, alias]);
  assert.equal((await sql`SELECT count(*)::int AS n FROM presentation_email_jobs`)[0].n, 0, 'source reconciliation sends no email');
  const objects = new Map<string, Buffer>(), deletes: string[] = [], mail: Array<{ recipient: string; subject: string; html: string }> = [];
  const storage = { publicBaseUrl: 'https://test.r2.dev', putObject: async (input: { key: string; body: Buffer }) => { objects.set(input.key, Buffer.from(input.body)); }, deleteObject: async (key: string) => { deletes.push(key); objects.delete(key); } };
  const app = Fastify({ logger: false }); t.after(() => app.close());
  await app.register(jwt, { secret: 'synthetic-poster-workflow-secret' }); await app.register(multipart);
  app.setErrorHandler((error, _request, reply) => {
    if (error instanceof ApiError) return reply.code(error.statusCode).send(error.toJSON());
    return reply.code(500).send({ success: false, code: 'SYNTHETIC_INTERNAL_ERROR' });
  });
  app.addHook('preHandler', async request => { await request.jwtVerify(); });
  app.register(presentationOwnerRoutes, { prefix: '/api/abstracts', database, storage });
  app.register(presentationBackofficeRoutes, { prefix: '/api/backoffice', database }); await app.ready();
  // Synthetic sessions for actual seed accounts; production login/locale is separately covered by UI tests.
  const admin = { authorization: `Bearer ${app.jwt.sign(f.admin)}` }, owner = { authorization: `Bearer ${app.jwt.sign(f.owner)}` };
  const base = `/api/backoffice/events/${f.eventId}`;
  const get = async <T>(url: string, headers = admin): Promise<T> => {
    const result = await app.inject({ method: 'GET', url, headers }); assert.equal(result.statusCode, 200, result.body); return result.json().data;
  };
  const post = async <T>(url: string, input: unknown, status = 201, key = randomUUID()): Promise<T> => {
    const result = await app.inject({ method: 'POST', url, headers: { ...admin, 'idempotency-key': key }, payload: input as Record<string, unknown> });
    assert.equal(result.statusCode, status, result.body); return result.json().data;
  };
  const initialList = await get<PresentationListDto>(base + '/presentation-targets');
  const pendingAlias = initialList.items.find(row => row.abstractId === second.id)!;
  assert.equal(pendingAlias.matchState, 'alias_pending');
  await post(base + '/presentation-verifications', { sourceKey: pendingAlias.sourceKey, fingerprint: pendingAlias.matchFingerprint, reason: 'Checked exact old ID and both snapshots' });
  const ready = await get<PresentationListDto>(base + '/presentation-targets'); assert.equal(ready.items.filter(row => row.canNotify).length, 2);
  assert.equal(ready.items.find(row => row.abstractId === second.id)!.verifiedBy, f.adminId);
  const preview = await post<PresentationPreviewDto>(base + '/presentation-email-previews', { kind: 'initial', abstractIds: [f.abstractId, second.id] }, 200);
  assert.equal(preview.messages.length, 2); assert.deepEqual(preview.messages.map(message => message.recipient), [f.owner.email, f.owner.email]);
  const batch = await post<{ batchId: string; queued: number }>(base + '/presentation-notification-batches', { kind: 'initial', abstractIds: [f.abstractId, second.id], previewFingerprint: preview.fingerprint }, 202);
  assert.equal(batch.queued, 2);
  const drain = async () => { while (await runPresentationMailOnce(database, { send: async input => { mail.push(input); return { providerMessageId: `synthetic-${mail.length}` }; } })) {} };
  await drain(); assert.equal(mail.length, 2); assert.ok(mail.every(message => message.recipient === f.owner.email));
  const batchStatus = await get<{ jobs: Array<{ abstractId: number; state: string }> }>(`${base}/presentation-notification-batches/${batch.batchId}`);
  assert.deepEqual(batchStatus.jobs.map(job => job.state), ['sent', 'sent']);
  assert.deepEqual(new Set(batchStatus.jobs.map(job => job.abstractId)), new Set([f.abstractId, second.id]));
  const upload = async (bytes: Buffer, name: string, mime: string, requestId?: string, key = randomUUID()) => {
    const boundary = 'synthetic-workflow-boundary';
    const payload = Buffer.concat([Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="file"; filename="${name}"\r\nContent-Type: ${mime}\r\n\r\n`), bytes, Buffer.from(`\r\n${requestId ? `--${boundary}\r\nContent-Disposition: form-data; name="requestId"\r\n\r\n${requestId}\r\n` : ''}--${boundary}--\r\n`)]);
    return app.inject({ method: 'POST', url: `/api/abstracts/${f.abstractId}/presentation-uploads`, headers: { ...owner, 'content-type': `multipart/form-data; boundary=${boundary}`, 'idempotency-key': key }, payload });
  };
  const png = await sharp({ create: { width: 5, height: 7, channels: 4, background: '#ffffff' } }).png().toBuffer();
  const rejected = await upload(png, 'first.png', 'image/png'); assert.equal(rejected.statusCode, 415);
  const disguised = await upload(png, 'first.pdf', 'application/pdf'); assert.equal(disguised.statusCode, 415); assert.equal(objects.size, 0);
  const initialDocument = await PDFDocument.create(); initialDocument.addPage(); const initialPdf = Buffer.from(await initialDocument.save());
  const firstKey = randomUUID(), first = await upload(initialPdf, 'first.pdf', 'application/pdf', undefined, firstKey); assert.equal(first.statusCode, 201, first.body);
  const firstFile = first.json().data.upload as UploadDto;
  const firstReplay = await upload(initialPdf, 'first.pdf', 'application/pdf', undefined, firstKey); assert.equal(firstReplay.statusCode, 201); assert.deepEqual(firstReplay.json().data.upload, firstFile);
  const locked = await get<OwnerPresentationDto>(`/api/abstracts/${f.abstractId}/presentation`, owner); assert.equal(locked.canUpload, false); assert.equal(locked.currentUpload!.version, 1);
  await drain(); assert.equal(mail.length, 3, 'one automatic receipt for initial acceptance/replay');
  const deadline = new Date(Date.now() + 3600000).toISOString(), details = 'Revise the synthetic figure legend';
  const draft = await post<PresentationPreviewDto>(base + '/presentation-email-previews', { kind: 'revision', abstractId: f.abstractId, details, closesAt: deadline }, 200);
  const revision = await post<{ request: RevisionDto }>(`${base}/presentation-targets/${f.abstractId}/revision-requests`, { requestId: draft.requestId, details, closesAt: draft.closesAt, previewFingerprint: draft.fingerprint });
  assert.equal((await get<OwnerPresentationDto>(`/api/abstracts/${f.abstractId}/presentation?requestId=${revision.request.id}`, owner)).currentUpload!.id, firstFile.id);
  await drain(); const document = await PDFDocument.create(); document.addPage(); const pdf = Buffer.from(await document.save());
  const rejectedRevision = await upload(png, 'revision.png', 'image/png', revision.request.id); assert.equal(rejectedRevision.statusCode, 415); assert.equal(objects.size, 1);
  const revised = await upload(pdf, 'revision.pdf', 'application/pdf', revision.request.id); assert.equal(revised.statusCode, 201, revised.body);
  const secondFile = revised.json().data.upload as UploadDto; assert.equal(secondFile.version, 2); assert.equal(secondFile.revisionRequestId, revision.request.id);
  await drain(); assert.equal(mail.length, 5, 'initial pair + first receipt + revision notice + revision receipt');
  const nextPreview = await post<PresentationPreviewDto>(base + '/presentation-email-previews', { kind: 'revision', abstractId: f.abstractId, details: 'Another request', closesAt: deadline }, 200);
  const next = await post<{ request: RevisionDto }>(`${base}/presentation-targets/${f.abstractId}/revision-requests`, { requestId: nextPreview.requestId, details: 'Another request', closesAt: nextPreview.closesAt, previewFingerprint: nextPreview.fingerprint });
  await post(`${base}/presentation-revision-requests/${next.request.id}/cancellations`, { reason: 'Synthetic replacement required' });
  const oldLink = await get<OwnerPresentationDto>(`/api/abstracts/${f.abstractId}/presentation?requestId=${next.request.id}`, owner);
  assert.equal(oldLink.blockCode, 'PRESENTATION_REQUEST_CANCELLED'); assert.equal(oldLink.canUpload, false);
  const blocked = await upload(pdf, 'cancelled.pdf', 'application/pdf', next.request.id); assert.equal(blocked.statusCode, 409); assert.equal(blocked.json().code, 'PRESENTATION_REQUEST_CANCELLED');
  await drain(); assert.equal(mail.length, 5, 'cancelled queued notice is suppressed rather than sent');
  const history = await get<PresentationDetailDto>(`${base}/presentation-targets/${f.abstractId}`);
  assert.deepEqual(history.uploads.map(file => file.version), [2, 1]); assert.equal(history.row.currentUpload!.id, secondFile.id);
  assert.deepEqual(new Set(history.requests.map(request => request.status)), new Set(['submitted', 'cancelled']));
  assert.ok(history.audit.length >= 3); assert.equal(history.emailJobs.filter(job => job.kind === 'receipt').length, 2);
  assert.ok(history.emailJobs.some(job => job.kind === 'revision' && job.state === 'suppressed'));
  assert.equal(objects.size, 2); assert.deepEqual(deletes, []);
  assert.deepEqual([...objects.values()], [initialPdf, pdf]);
  assert.ok([...objects.keys()].every(key => key.startsWith(`events/${f.eventId}/presentations/${f.abstractId}/`)));
  console.log('A04/A09/A10/A13/A15/A18/A22 synthetic actual-route chain PASS; fake mail=5, original objects=2, retained versions=2, requests=2, no real providers');
});
